# Get an already existing image of ubuntu 20.04
FROM nvidia/cudagl:11.1.1-base-ubuntu20.04

# Minimal setup
RUN apt-get update && apt-get install -y \
    curl \
    locales \
    lsb-release \
    gnupg2 \
    mesa-utils \
    apt-transport-https

# Install packages without prompting the user to answer any questions
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales

# Install ROS Noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

RUN echo 'export LIBGL_ALWAYS_INDIRECT=1' >> ~/.bashrc

# Installing ROS and dependencies
RUN apt-get update && apt-get install -y \
    ros-noetic-desktop-full \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    build-essential

# Initialize rosdep
RUN rosdep init && rosdep update

# Source ROS
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# Install Franka packages
RUN apt-get update && apt-get install -y \
    ros-noetic-libfranka \
    ros-noetic-franka-ros

RUN mkdir -p franka_ws/src

RUN bash -c "source /opt/ros/noetic/setup.bash"

# wget http://ftp.kr.debian.org/debian/pool/main/i/init-system-helpers/init-system-helpers_1.60_all.deb
# sudo apt install init-system-helpers_1.60_all.deb

# wget https://github.com/iROSA-lab/Docker_env_Tiago/blob/main/nvidia-scripts.sh

# bash nvidia-scripts.sh
# sudo apt install -y nvidia-docker2
# sudo systemctl daemon-reload
# sudo systemctl restart docker


# xhost +

# docker build -t franka .

# docker run -it --net=host --gpus all \
#     --privileged \
#     --env="NVIDIA_DRIVER_CAPABILITIES=all" \
#     --env="DISPLAY" \
#     --env="QT_X11_NO_MITSHM=1" \
#     --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
#     -v "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK" -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK\
#     --name="franka_nvidia"\
#     franka_nvidia \
#     bash


# docker start franka
# xhost +
# docker exec -it franka bash
# docker stop franka