# Get an already existing image of ubuntu 20.04
FROM ubuntu:20.04

# Minimal setup
RUN apt-get update && apt-get install -y \
    curl \
    locales \
    lsb-release \
    gnupg2 \
    mesa-utils \
    apt-transport-https

# Install packages without prompting the user to answer any questions
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales

# Install ROS Noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

# Installing ROS and dependencies
RUN apt-get update && apt-get install -y \
    ros-noetic-desktop-full \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    build-essential

# Install Moveit!
RUN apt-get update -q && \
    apt-get dist-upgrade -q -y && \
    apt-get install -y ros-noetic-moveit && \
    rm -rf /var/lib/apt/lists/*

# Initialize rosdep
RUN rosdep init && rosdep update

# Source ROS
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# Setup ROS workspace
RUN mkdir -p /opt/ros_ws/src
WORKDIR /opt/ros_ws
RUN  . /opt/ros/noetic/setup.sh && \
	    catkin_make 

RUN echo "source /opt/ros_ws/devel/setup.bash" >> ~/.bashrc

# Install libfranka
WORKDIR /opt/
RUN apt-get update
RUN apt-get install build-essential cmake git libpoco-dev libeigen3-dev

ARG libfranka_version=0.10.0

RUN git clone --recursive https://github.com/frankaemika/libfranka \
    && cd libfranka \
    && git checkout $libfranka_version \
    && git submodule update \
    && mkdir build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF .. \
    && cmake --build . \
    && cpack -G DEB \
    && dpkg -i libfranka*.deb

# Install franka_ros
ARG frankaros_version=0.10.0

WORKDIR /opt/ros_ws/src/
RUN git clone --recursive https://github.com/frankaemika/franka_ros \
    && cd franka_ros \
    && git checkout $frankaros_version 

WORKDIR /opt/ros_ws/
RUN . /opt/ros/noetic/setup.sh \
    && rosdep install --from-paths src --ignore-src --rosdistro noetic -y --skip-keys libfranka \
    && catkin_make -DCMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=/path/to/libfranka/build

# Install franka_zed_gazebo
RUN cd src && \
        git clone https://github.com/iROSA-lab/franka_zed_gazebo.git 

RUN  . /opt/ros/noetic/setup.sh && \
	    catkin_make --pkg franka_zed_gazebo

RUN bash -c "source /opt/ros_ws/devel/setup.bash"
RUN bash -c "source /opt/ros/noetic/setup.bash"

# wget http://ftp.kr.debian.org/debian/pool/main/i/init-system-helpers/init-system-helpers_1.60_all.deb
# sudo apt install init-system-helpers_1.60_all.deb

# xhost +

# docker build -t franka .

# docker run -it --net=host \
#     --privileged \
#     --env="DISPLAY" \
#     --env="QT_X11_NO_MITSHM=1" \
#     --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
#     -v "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK" -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK\
#     --name="franka"\
#     franka \
#     bash

# docker start franka
# xhost +
# docker exec -it franka bash
# docker stop franka