# Get an already existing image of ubuntu 20.04
FROM nvidia/cudagl:11.1.1-base-ubuntu20.04

# Minimal setup
RUN apt-get update && apt-get install -y \
    curl \
    locales \
    lsb-release \
    gnupg2 \
    mesa-utils \
    apt-transport-https \
    git \
    wget \
    ipython3

# Install packages without prompting the user to answer any questions
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales

# Install ROS Noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

RUN echo 'export LIBGL_ALWAYS_INDIRECT=1' >> ~/.bashrc

# Installing ROS and dependencies
RUN apt-get update && apt-get install -y \
    ros-noetic-desktop-full \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    python3-catkin-tools \
    python-is-python3 \
    ros-noetic-actionlib-tools \
    ros-noetic-moveit-commander \
    build-essential 

# Initialize rosdep
RUN rosdep init && rosdep update

# Source ROS
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# create the workspace directory
RUN mkdir -p tiago_dual_public_ws/src

# install tiago_dual_public packages
RUN wget https://raw.githubusercontent.com/pal-robotics/tiago_dual_tutorials/master/tiago_dual_public-noetic.rosinstall
RUN rosinstall tiago_dual_public_ws/src /opt/ros/noetic tiago_dual_public-noetic.rosinstall

# install dependencies
RUN rosdep update
RUN rosdep install -y --from-paths tiago_dual_public_ws/src --ignore-src --rosdistro noetic --skip-keys "urdf_test omni_drive_controller \
                orocos_kdl pal_filters libgazebo9-dev pal_usb_utils speed_limit_node camera_calibration_files pal_moveit_plugins \
                pal_startup_msgs pal_local_joint_control pal_pcl_points_throttle_and_filter current_limit_controller hokuyo_node \
                dynamixel_cpp pal_moveit_capabilities pal_pcl dynamic_footprint gravity_compensation_controller pal-orbbec-openni2 \
                pal_loc_measure pal_map_manager joint_impedance_trajectory_controller ydlidar_ros_driver"

# build the workspace
RUN bash -c "source /opt/ros/noetic/setup.bash \
    && cd tiago_dual_public_ws/\
    && catkin build -DCATKIN_ENABLE_TESTING=0 -j $(expr `nproc` / 2) \
    && echo 'source tiago_dual_public_ws/devel/setup.bash' >> ~/.bashrc"
