# This workflow will build a new container image and push it to Docker Hub
# whenever a new commit is pushed to the repository.
on: push
# The jobs section of the workflow file contains a list of jobs.
jobs:
  build-container:
    name: Build & publish robot images
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # the combination of robots and dockerfiles to build
    strategy:
      matrix:
        include:
          - robot: tiago
            file: Docker_tiago/Dockerfile_nvidia
          - robot: tiago_wo_nvidia
            file: Docker_tiago/Dockerfile_no_GPU
          - robot: franka
            file: Docker_franka/Dockerfile_nvidia
          - robot: franka_wo_nvidia
            file: Docker_franka/Dockerfile_no_GPU
          - robot: franka_real
            file: Docker_franka/Dockerfile_franka_real
      max-parallel: 1
      fail-fast: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # logs into docker hub
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # build and push the container
      - name: build and publish
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pearl_robots:${{ matrix.robot }}
          labels: ${{ secrets.DOCKER_USERNAME }}/pearl_robots:${{ matrix.robot }}
          file: ${{ matrix.file }}
